---
title: Épreuve de NSI au bac en Terminale
lang: fr
tbl-cap-location: bottom
crossref: 
    eq-prefix: Éq.
    tbl-prefix: Tableau
    tbl-title: Tableau
format:
    html: default
---

## Programme officiel

[Fichier à télécharger...](../assets/pdf/Programme_Term_NSI.pdf){ target=_blank }

## Nature de l'épreuve de NSI au bac en Terminale

D'après le [Bulletin Officiel n°36 du 30 septembre 2022](https://www.education.gouv.fr/bo/22/Hebdo36/MENE2226770N.htm){ target=_blank} :

* **Durée** : 3 heures 30 + 1 heure
* **Coefficient** : 16
* **Format** : L'épreuve terminale obligatoire de spécialité est composée de deux parties : 

    * une partie écrite, notée sur 20 et comptant pour 75 % de la note finale ;
    * une partie pratique, notée sur 20 et comptant pour 25 % de la note finale.s

**Partie écrite de l'épreuve de NSI au bac en terminale**

* **Durée** : 3 heures 30
* **Modalités** : La partie écrite consiste en la résolution de trois exercices permettant d'évaluer les connaissances et les capacités attendues conformément aux programmes de première et de terminale de la spécialité.
    
    Le sujet comporte trois exercices indépendants les uns des autres, qui permettent d'évaluer les connaissances et compétences des candidats.

### Points du programme évaluables lors de l'épreuve écrite

La totalité du programme de NSI de terminale est évaluée lors de l'épreuve écrite.

## Partie pratique de l'épreuve de NSI au bac en terminale

* **Durée** : 1 heure
* **Modalités** : La partie pratique consiste en la résolution de deux exercices sur ordinateur, chacun étant noté sur 10 points.
    
    Le candidat est évalué sur la base d'un dialogue avec un professeur-examinateur.
    
    Un examinateur évalue au maximum quatre élèves. L'examinateur ne peut pas évaluer un élève qu'il a eu en classe durant l'année en cours.
    
    L'évaluation de cette partie se déroule en fin de troisième trimestre. 
    
    * **Premier exercice**

        Le premier exercice consiste à programmer un algorithme figurant explicitement au programme, ne présentant pas de difficulté particulière, dont on fournit une spécification.

        Il s'agit donc de restituer un algorithme rencontré et travaillé à plusieurs reprises en cours de formation.
        
        Le sujet peut proposer un jeu de test avec les réponses attendues pour permettre au candidat de vérifier son travail.

    * **Deuxième exercice**

        Pour le second exercice, un programme est fourni au candidat.
        
        Cet exercice ne demande pas l'écriture complète d'un programme, mais permet de valider des compétences de programmation suivant des modalités variées : le candidat doit, par exemple, compléter un programme « à trous » afin de répondre à une spécification donnée, ou encore compléter un programme pour le documenter, ou encore compléter un programme en ajoutant des assertions, etc.
