project:
  type: website

website:
  title: "NSI - Terminale"
  favicon: favicon.ico
  page-navigation: true
  site-url: https://tnsi.sitelf.fr
  repo-url: https://github.com/fabricelallemand15/quarto_TNSI
  repo-actions: [issue]
  reader-mode: true
  navbar:
    search: false
    background: "#2c3e50"
    left:
      - href: index.qmd
        text: "{{< fa house-chimney-window >}} Accueil"
      - href: https://python.sitelf.fr/
        text: "{{< fa brands python >}} Console Python"
      - href: https://notebook.sitelf.fr/
        text: "{{< fa pen-to-square >}} Notebook Python"
      - href: ressources.qmd
        text: "{{< fa info >}} Sources"
  sidebar: 
    style: floating
    collapse-level: 1
    alignment: left
    contents: 
      - section: "Ch. 1 - Programmation orientée objet"
        contents: 
            - 01-langagesProgr/POO_cours.qmd
            - 01-langagesProgr/POO_complements.qmd
            - 01-langagesProgr/POO_exercices.qmd
            - 01-langagesProgr/TPPOOBataille.qmd
      - section: "Ch. 2 - Récursivité"
        contents: 
            - 01-langagesProgr/recursivite_cours.qmd
            - 01-langagesProgr/recursivite_exercices.qmd
            - 01-langagesProgr/paradigmes_cours.qmd
            - 01-langagesProgr/paradigmes_exercices.qmd
            - 01-langagesProgr/TPHanoi.qmd 
      - section: "Ch. 3 - Structures linéaires : listes, piles, files et dictionnaires - Interface et implémentation"
        contents:
          - 02-structures/interfaces_cours.qmd
          - 02-structures/listes_cours.qmd
          - 02-structures/piles_cours.qmd
          - 02-structures/files_cours.qmd
          - 02-structures/listes_exercices.qmd
          - 02-structures/dictionnaires_cours.qmd
          - 02-structures/dictionnaires_exercices.qmd
          - 02-structures/TPDictionnaire.qmd
          - 02-structures/projet_detecteur_langue.qmd
          # - 02-structures/bilan.qmd
      - section: "Ch. 4 - Bases de données"
        contents: 
          - 03-BDD/partie1.qmd
          - 03-BDD/partie2.qmd
          - 03-BDD/sql_cours.qmd
          - 03-BDD/exercices.qmd
          - 03-BDD/TP1.qmd
          - 03-BDD/TP2.qmd
          - 03-BDD/TP3.qmd
          - 03-BDD/projet_BDD.qmd
      - section: "Ch. 5 - Arbres binaires"
        contents: 
          - 04-arbres/arbres_cours.qmd
          - 04-arbres/arbres_exercices.qmd
          - 04-arbres/implementationArbres.qmd
          - 04-arbres/TParbres.qmd
          - 06-algo/index.qmd
          - 06-algo/rappels.qmd
          - 06-algo/algo_arbres_cours.qmd
          - 06-algo/algo_arbres_exos.qmd
      - section: "Ch. 6 - Graphes"
        contents:
          - 08-graphes/index_graphes.qmd
          - 08-graphes/graphes_cours.qmd
          - 08-graphes/tp_graphe_matrice.ipynb
          - 08-graphes/tp_graphe_liste.ipynb
          - 08-graphes/graphes_exercices.qmd 
          - 11-algos2/dfs_graphe.qmd
          - 11-algos2/bfs_graphe.qmd
          - 11-algos2/exos_graphes.qmd
      - section: "Ch. 7 - Sécurité et réseaux"
        contents: 
          - 07-reseaux/adressesIP.qmd
          - 07-reseaux/routage_cours.qmd
          - 07-reseaux/routage_exos.qmd
          - 09-reseaux2/HTTPS_cours.qmd
      - section: "Ch. 8 - Stratégies algorithmiques avancées"
        contents:
          - 06-algo/diviser_pour_regner_cours.qmd
          - 06-algo/diviser_pour_regner_exos.qmd
          - 16-ProgDyn/ProgDyn_Cours.qmd
          - 16-ProgDyn/ProgDyn_Exos.qmd 
          - 17-RechercheTextuelle/cours.ipynb
      - section: "Ch. 9 - Systèmes sur puce et Processus"
        contents: 
          - 19-SystPuces/SystPuces_cours.qmd
          - 19-SystPuces/SystPuces_exos.qmd
          - 05-archiSE/processus_cours.qmd
          - 05-archiSE/processus_TP.qmd
          - 05-archiSE/processus_exos.qmd
          - 05-archiSE/processus_python.qmd
      - section: "Ch. 10 - Limites du calculable"
        contents: 
          - 10-langages_prog2/calculabilite.qmd
      - section: "Histoire de l'informatique"
        contents: 
          - histoire/index.qmd
      - section: "Baccalauréat"
        contents: 
          - bac/index.qmd
          - bac/annales.qmd
      - section: "Grand Oral"
        contents: 
          - GrandOral/index.qmd
  page-footer: 
    left:
      - href: http://creativecommons.org/licenses/by/4.0/
        text: <img alt="Licence Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" />
    right: 
      - text: "Mentions légales"
        href: about.qmd
      - icon: github
        href: https://github.com/fabricelallemand15/quarto_TNSI
  cookie-consent: true

bibliography: references.bib 

format:
  html:
    lang: fr
    link-external-icon: true
    theme:
      light: [flatly, theme_light.scss]
      dark: [darkly, theme_dark.scss]
    css: styles.css
    toc: true
    toc-location: right
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 300px
    lightbox: auto
    code-block-border-left: "#31BAE9"
    code-block-bg: true
    include-in-header: 
      file: matomo.html
